
## v1.0
## updated with resource limits
##  Note: PODs will stop if exceed resource limit

---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-webapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        resources:
            requests:
              memory: "1Gi"  # Minimum memory to allocate
              cpu: "0.5"      # Minimum CPU to allocate (1 cpu)
            limits:
              memory: "2Gi"  # Maximum memory allowed
              cpu: "1"         # Maximum CPU allowed (1 cpu)
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mysql"
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-webapp
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
  clusterIP: None  # Headless service
